### ISSUE TITLE
SyntaxError: Invalid regular expression: /.{1,0}/

### ISSUE THREAD

**Issue by ianbrandt** [Freyskeyd/gulp-prompt#28] opened 2016-09-07 21:56 UTC
I get the error below trying to use gulp-prompt from within IntelliJ IDEA 2016.2.3 on OS X.  It works fine if I invoke the same task via `gulp` from Terminal.app.  It appears a newer build of Inquirer may fix this issue per SBoudrias/Inquirer.js#290.

```
? Are you sure? (y/N) [14:42:56] '<anonymous>' errored after 35 ms
[14:42:56] SyntaxError: Invalid regular expression: /.{1,0}/: numbers out of order in {} quantifier.
    at new RegExp (native)
    at breakLines (/Users/ibrandt/Development/git/myproject/node_modules/gulp-prompt/node_modules/inquirer/lib/utils/screen-manager.js:108:15)
    at [object Object].ScreenManager.render (/Users/ibrandt/Development/git/myproject/node_modules/gulp-prompt/node_modules/inquirer/lib/utils/screen-manager.js:55:22)
    at Prompt.render (/Users/ibrandt/Development/git/myproject/node_modules/gulp-prompt/node_modules/inquirer/lib/prompts/confirm.js:85:15)
    at Prompt._run (/Users/ibrandt/Development/git/myproject/node_modules/gulp-prompt/node_modules/inquirer/lib/prompts/confirm.js:65:8)
    at Prompt.run (/Users/ibrandt/Development/git/myproject/node_modules/gulp-prompt/node_modules/inquirer/lib/prompts/base.js:57:8)
    at Object.<anonymous> (/Users/ibrandt/Development/git/myproject/node_modules/gulp-prompt/node_modules/inquirer/lib/ui/prompt.js:84:12)
    at module.exports (/Users/ibrandt/Development/git/myproject/node_modules/run-async/index.js:15:21)
    at AnonymousObservable.__subscribe (/Users/ibrandt/Development/git/myproject/node_modules/gulp-prompt/node_modules/inquirer/lib/utils/utils.js:16:7)
    at AnonymousObservable.tryCatcher (/Users/ibrandt/Development/git/myproject/node_modules/rx-lite/rx.lite.js:63:31)
    at setDisposable (/Users/ibrandt/Development/git/myproject/node_modules/rx-lite/rx.lite.js:5741:44)
    at AnonymousObservable.innerSubscribe [as _subscribe] (/Users/ibrandt/Development/git/myproject/node_modules/rx-lite/rx.lite.js:5755:9)
    at AnonymousObservable.Rx.Observable.observableProto.subscribe.observableProto.forEach (/Users/ibrandt/Development/git/myproject/node_modules/rx-lite/rx.lite.js:1604:19)
    at AnonymousObservable.__subscribe (/Users/ibrandt/Development/git/myproject/node_modules/rx-lite/rx.lite.js:2112:21)
    at AnonymousObservable.tryCatcher (/Users/ibrandt/Development/git/myproject/node_modules/rx-lite/rx.lite.js:63:31)
    at setDisposable (/Users/ibrandt/Development/git/myproject/node_modules/rx-lite/rx.lite.js:5741:44)
[14:42:56] 'deploy' errored after 162 ms
```

**Comment by jonasof** [comment] 2016-10-08 18:31
Same issue with Netbeans 8.2 terminal.

**Comment by amooz** [comment] 2016-11-16 14:38
I'm also encountering this issue

**Comment by giovannigiordano** [comment] 2016-11-18 13:49
Update to latest version of InquirerJS, this is a bug of an older version.

**Comment by jwaltonmedia** [comment] 2016-12-07 21:49
Any progress on this?

**Comment by giovannigiordano** [comment] 2016-12-07 21:52
I've made a pull request but he hasn't merge. The fix is upgrade of
inquirerjs and update of export module in index.js

Il 07 dic 2016 10:49 PM, "James Walton" <notifications@github.com> ha
scritto:

**Comment by jasondsouza18** [comment] 2017-09-07 18:07
I had the same problem using Git Bash on Windows 10, problem solved when used Command line.

**Comment by shannonlal** [comment] 2017-09-25 23:55
Is this still an issue?  The latest version of gulp-prompt upgraded to version 3 of inquirer.js and wanted to know if anyone is still able to reproduce this.

**Comment by shannonlal** [comment] 2017-10-05 00:12
I am going to close this off since this there seems to be a work around with using command line on windows

**Closed by shannonlal** 2017-10-05 00:12 UTC
