### ISSUE TITLE
Type 'Radio' a 'Checkbox' not working properly if first question

### ISSUE THREAD

**Issue by DruMasterMunch** [Freyskeyd/gulp-prompt#27] opened 2016-08-05 09:06 UTC
I have this issue when trying to use Radios or Checkboxes: 
If it's the first question asked, i can't navigate through the answers with the arrows, can't select with spacebar, et if i press enter it fail...

This issue is fixed when i add another question first, a simple confirm question for example ... In this case i have the common behavior, i can choose my answer and select it with spacebar.

Do you have a fix for this ?

**Comment by shannonlal** [comment] 2017-09-25 12:21
Can you provide an example on how to replicate this?  Do you have a sample gulp task that can easily reproduce this.

**Comment by shannonlal** [comment] 2017-10-11 00:20
I am going to close this issue out since I have provided a sample gulpfile (gulp-prompt/examples/first-choise-selection-gulpfile.js) that illustrates how you can define a selection and select the first item in the list.  If there are any issues or someone is still able to reproduce the bug please re-open the issue.

Thanks

**Closed by shannonlal** 2017-10-11 00:20 UTC
